from crewai import Agent
from typing import Dict, List
from langchain_core.language_models.chat_models import BaseChatModel

class HashtagSpecialist:
    @staticmethod
    def create(llm: BaseChatModel) -> Agent:
        """
        Creates a Hashtag Specialist agent that generates relevant hashtags.
        
        Args:
            llm (BaseChatModel): The language model to use for the agent
        """
        return Agent(
            role='Hashtag Specialist',
            goal='Generate relevant and trending hashtags for social media content',
            backstory="""You are a hashtag expert who understands trending topics 
            and hashtag optimization across different social media platforms. You 
            know how to mix trending, niche, and branded hashtags for maximum reach.""",
            tools=[],  # Will add hashtag research tools later
            llm=llm,
            verbose=True
        )

    @staticmethod
    def generate_hashtags(content: Dict, platform: str) -> dict:
        """
        Generates hashtags based on the content and platform.
        
        Args:
            content (Dict): Generated content from Content Writer
            platform (str): Target social media platform
            
        Returns:
            dict: Generated hashtags in different categories
        """
        hashtags = {
            "trending": [],
            "niche": [],
            "branded": [],
            "platform_specific": {
                "platform": platform,
                "recommended_count": 0,
                "max_count": 0
            },
            "performance_metrics": {
                "reach_potential": 0,
                "engagement_rate": 0
            }
        }
        
        # Hashtags will be generated by the agent during execution
        return hashtags

    @staticmethod
    def optimize_hashtag_count(hashtags: List[str], platform: str) -> List[str]:
        """
        Optimizes the number of hashtags based on platform best practices.
        
        Args:
            hashtags (List[str]): List of generated hashtags
            platform (str): Target social media platform
            
        Returns:
            List[str]: Optimized list of hashtags
        """
        platform_limits = {
            "instagram": 30,
            "twitter": 2,
            "linkedin": 3,
            "facebook": 2,
            "tiktok": 5
        }
        
        max_hashtags = platform_limits.get(platform.lower(), 5)
        return hashtags[:max_hashtags] 